-- =============================================================================
-- BASE DE DATOS RENFI - POSTGRESQL / SUPABASE
-- Compatible al 100% con Supabase (SQL Editor / Migraciones) y PostgreSQL 12+
-- Proyecto: Renfi (FrontEnd & Backend API)
-- =============================================================================

-- =============================================================================
-- 1. EXTENSIONES
-- =============================================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- 2. ELIMINACIÓN DE TABLAS PREVIAS (ORDEN DE DEPENDENCIAS INVERSO)
-- =============================================================================
DROP TABLE IF EXISTS public."Pago" CASCADE;
DROP TABLE IF EXISTS public."Factura" CASCADE;
DROP TABLE IF EXISTS public."Reserva" CASCADE;
DROP TABLE IF EXISTS public."MetodoDePago" CASCADE;
DROP TABLE IF EXISTS public."Imagen" CASCADE;
DROP TABLE IF EXISTS public."Finca" CASCADE;
DROP TABLE IF EXISTS public."Municipio" CASCADE;
DROP TABLE IF EXISTS public."Usuario" CASCADE;
DROP TABLE IF EXISTS public."Rol" CASCADE;

-- =============================================================================
-- 3. CREACIÓN DE TABLAS CON IDENTIFICADORES EXACTOS (PASCALCASE)
-- =============================================================================

-- Tabla: Rol
CREATE TABLE public."Rol" (
    "IdRol" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NombreRol" VARCHAR(300) NOT NULL
);

-- Tabla: Usuario
CREATE TABLE public."Usuario" (
    "NumeroDocumento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdRol" INT REFERENCES public."Rol"("IdRol") ON UPDATE CASCADE ON DELETE SET NULL,
    "NombreUsuario" VARCHAR(300) NOT NULL,
    "ApellidoUsuario" VARCHAR(300) NOT NULL,
    "Telefono" VARCHAR(100),
    "Contrasena" VARCHAR(300) NOT NULL,
    "Correo" VARCHAR(500) NOT NULL UNIQUE,
    "Estado" VARCHAR(150) DEFAULT 'Activo'
);

-- Tabla: Municipio
CREATE TABLE public."Municipio" (
    "IdMunicipio" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NombreMunicipio" VARCHAR(150) NOT NULL
);

-- Tabla: Finca
CREATE TABLE public."Finca" (
    "IdFinca" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdMunicipio" INT REFERENCES public."Municipio"("IdMunicipio") ON UPDATE CASCADE ON DELETE SET NULL,
    "NumeroDocumentoUsuario" INT REFERENCES public."Usuario"("NumeroDocumento") ON UPDATE CASCADE ON DELETE SET NULL,
    "NombreFinca" VARCHAR(300) NOT NULL,
    "Direccion" VARCHAR(500),
    "InformacionAdicional" VARCHAR(500),
    "Capacidad" INT DEFAULT 1,
    "Precio" INT DEFAULT 0,
    "Estado" VARCHAR(150) DEFAULT 'Disponible',
    "Calificacion" INT DEFAULT 5
);

-- Tabla: Imagen
CREATE TABLE public."Imagen" (
    "IdImagen" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UrlImagen" VARCHAR(500) NOT NULL,
    "IdFinca" INT REFERENCES public."Finca"("IdFinca") ON UPDATE CASCADE ON DELETE CASCADE
);

-- Tabla: MetodoDePago
CREATE TABLE public."MetodoDePago" (
    "IdMetodoDePago" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NombreMetodoDePago" VARCHAR(150) NOT NULL,
    "PagoMixto" BOOLEAN DEFAULT FALSE
);

-- Tabla: Reserva
CREATE TABLE public."Reserva" (
    "IdReserva" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdFinca" INT REFERENCES public."Finca"("IdFinca") ON UPDATE CASCADE ON DELETE CASCADE,
    "NumeroDocumentoUsuario" INT REFERENCES public."Usuario"("NumeroDocumento") ON UPDATE CASCADE ON DELETE SET NULL,
    "FechaReserva" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "FechaEntrada" TIMESTAMP WITHOUT TIME ZONE,
    "FechaSalida" TIMESTAMP WITHOUT TIME ZONE,
    "Estado" VARCHAR(150) DEFAULT 'Pendiente',
    "MontoReserva" INT DEFAULT 0
);

-- Tabla: Factura
CREATE TABLE public."Factura" (
    "IdFactura" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdReserva" INT REFERENCES public."Reserva"("IdReserva") ON UPDATE CASCADE ON DELETE CASCADE,
    "FechaFactura" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "Total" INT DEFAULT 0
);

-- Tabla: Pago
CREATE TABLE public."Pago" (
    "IdPago" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdFactura" INT REFERENCES public."Factura"("IdFactura") ON UPDATE CASCADE ON DELETE CASCADE,
    "IdMetodoDePago" INT REFERENCES public."MetodoDePago"("IdMetodoDePago") ON UPDATE CASCADE ON DELETE SET NULL,
    "Monto" INT DEFAULT 0,
    "FechaPago" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "EstadoPago" VARCHAR(150) DEFAULT 'Pendiente'
);

-- =============================================================================
-- 4. ÍNDICES DE RENDIMIENTO Y BÚSQUEDA
-- =============================================================================
CREATE INDEX IF NOT EXISTS "idx_usuario_correo" ON public."Usuario"("Correo");
CREATE INDEX IF NOT EXISTS "idx_usuario_rol" ON public."Usuario"("IdRol");
CREATE INDEX IF NOT EXISTS "idx_finca_municipio" ON public."Finca"("IdMunicipio");
CREATE INDEX IF NOT EXISTS "idx_finca_usuario" ON public."Finca"("NumeroDocumentoUsuario");
CREATE INDEX IF NOT EXISTS "idx_imagen_finca" ON public."Imagen"("IdFinca");
CREATE INDEX IF NOT EXISTS "idx_reserva_finca" ON public."Reserva"("IdFinca");
CREATE INDEX IF NOT EXISTS "idx_reserva_usuario" ON public."Reserva"("NumeroDocumentoUsuario");
CREATE INDEX IF NOT EXISTS "idx_factura_reserva" ON public."Factura"("IdReserva");
CREATE INDEX IF NOT EXISTS "idx_pago_factura" ON public."Pago"("IdFactura");
CREATE INDEX IF NOT EXISTS "idx_pago_metodo" ON public."Pago"("IdMetodoDePago");

-- =============================================================================
-- 5. PROCEDIMIENTOS Y FUNCIONES ALMACENADAS (PL/pgSQL)
-- Compatibles con Supabase RPC: supabase.rpc('SP_Nombre', { ... })
-- y con consultas SQL directas: SELECT * FROM public."SP_Nombre"(...);
-- =============================================================================

--------------------------------------------------------------------------------
-- 5.1 ROL
--------------------------------------------------------------------------------

-- Listar roles
CREATE OR REPLACE FUNCTION public."SP_ListarRol"()
RETURNS TABLE (
    "IdRol" INT,
    "NombreRol" VARCHAR(300)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT r."IdRol", r."NombreRol"
    FROM public."Rol" r
    ORDER BY r."IdRol" ASC;
END;
$$;

-- Insertar rol (retorna IdRol generado)
CREATE OR REPLACE FUNCTION public."SP_InsertarRol"(
    "p_NombreRol" VARCHAR(300)
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO public."Rol" ("NombreRol")
    VALUES ("p_NombreRol")
    RETURNING "IdRol" INTO v_id;
    RETURN v_id;
END;
$$;

-- Actualizar rol
CREATE OR REPLACE FUNCTION public."SP_ActualizarRol"(
    "p_IdRol" INT,
    "p_NombreRol" VARCHAR(300)
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public."Rol"
    SET "NombreRol" = "p_NombreRol"
    WHERE "IdRol" = "p_IdRol";
END;
$$;

-- Eliminar rol
CREATE OR REPLACE FUNCTION public."SP_EliminarRol"(
    "p_IdRol" INT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM public."Rol"
    WHERE "IdRol" = "p_IdRol";
END;
$$;

--------------------------------------------------------------------------------
-- 5.2 USUARIOS Y AUTENTICACIÓN
--------------------------------------------------------------------------------

-- Listar todos los usuarios
CREATE OR REPLACE FUNCTION public."SP_ListarUsuarios"()
RETURNS TABLE (
    "NumeroDocumento" INT,
    "NombreUsuario" VARCHAR(300),
    "ApellidoUsuario" VARCHAR(300),
    "Telefono" VARCHAR(100),
    "Correo" VARCHAR(500),
    "Contrasena" VARCHAR(300),
    "Estado" VARCHAR(150),
    "IdRol" INT,
    "NombreRol" VARCHAR(300)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        u."NumeroDocumento",
        u."NombreUsuario",
        u."ApellidoUsuario",
        u."Telefono",
        u."Correo",
        u."Contrasena",
        u."Estado",
        r."IdRol",
        r."NombreRol"
    FROM public."Usuario" u
    INNER JOIN public."Rol" r ON u."IdRol" = r."IdRol"
    ORDER BY u."NumeroDocumento" ASC;
END;
$$;

-- Registrar usuario (retorna NumeroDocumento generado)
CREATE OR REPLACE FUNCTION public."SP_RegistrarUsuario"(
    "p_IdRol" INT,
    "p_NombreUsuario" VARCHAR(300),
    "p_ApellidoUsuario" VARCHAR(300),
    "p_Telefono" VARCHAR(100),
    "p_Correo" VARCHAR(300),
    "p_Contrasena" VARCHAR(300),
    "p_Estado" VARCHAR(150) DEFAULT 'Activo'
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO public."Usuario" (
        "IdRol", "NombreUsuario", "ApellidoUsuario", "Telefono", "Correo", "Contrasena", "Estado"
    ) VALUES (
        "p_IdRol", "p_NombreUsuario", "p_ApellidoUsuario", "p_Telefono", "p_Correo", "p_Contrasena", COALESCE("p_Estado", 'Activo')
    )
    RETURNING "NumeroDocumento" INTO v_id;
    RETURN v_id;
END;
$$;

-- Actualizar usuario
CREATE OR REPLACE FUNCTION public."SP_ActualizarUsuario"(
    "p_NumeroDocumento" INT,
    "p_IdRol" INT,
    "p_NombreUsuario" VARCHAR(300),
    "p_ApellidoUsuario" VARCHAR(300),
    "p_Telefono" VARCHAR(100),
    "p_Contrasena" VARCHAR(300),
    "p_Estado" VARCHAR(150)
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public."Usuario"
    SET "IdRol" = "p_IdRol",
        "NombreUsuario" = "p_NombreUsuario",
        "ApellidoUsuario" = "p_ApellidoUsuario",
        "Telefono" = "p_Telefono",
        "Contrasena" = "p_Contrasena",
        "Estado" = "p_Estado"
    WHERE "NumeroDocumento" = "p_NumeroDocumento";
END;
$$;

-- Iniciar sesión
CREATE OR REPLACE FUNCTION public."SP_IniciarSesion"(
    "p_Correo" VARCHAR(500),
    "p_Contrasena" VARCHAR(300)
)
RETURNS TABLE (
    "NumeroDocumento" INT,
    "IdRol" INT,
    "NombreUsuario" VARCHAR(300),
    "ApellidoUsuario" VARCHAR(300),
    "Telefono" VARCHAR(100),
    "Correo" VARCHAR(500),
    "Estado" VARCHAR(150),
    "NombreRol" VARCHAR(300)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        u."NumeroDocumento",
        u."IdRol",
        u."NombreUsuario",
        u."ApellidoUsuario",
        u."Telefono",
        u."Correo",
        u."Estado",
        r."NombreRol"
    FROM public."Usuario" u
    LEFT JOIN public."Rol" r ON u."IdRol" = r."IdRol"
    WHERE LOWER(u."Correo") = LOWER("p_Correo")
      AND u."Contrasena" = "p_Contrasena"
      AND u."Estado" = 'Activo';
END;
$$;

--------------------------------------------------------------------------------
-- 5.3 MUNICIPIOS
--------------------------------------------------------------------------------

-- Listar municipios
CREATE OR REPLACE FUNCTION public."SP_ListarMunicipios"()
RETURNS TABLE (
    "IdMunicipio" INT,
    "NombreMunicipio" VARCHAR(150)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT m."IdMunicipio", m."NombreMunicipio"
    FROM public."Municipio" m
    ORDER BY m."NombreMunicipio" ASC;
END;
$$;

-- Registrar municipio (retorna IdMunicipio)
CREATE OR REPLACE FUNCTION public."SP_RegistrarMunicipio"(
    "p_NombreMunicipio" VARCHAR(150)
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO public."Municipio" ("NombreMunicipio")
    VALUES ("p_NombreMunicipio")
    RETURNING "IdMunicipio" INTO v_id;
    RETURN v_id;
END;
$$;

-- Actualizar municipio
CREATE OR REPLACE FUNCTION public."SP_ActualizarMunicipio"(
    "p_IdMunicipio" INT,
    "p_NombreMunicipio" VARCHAR(150)
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public."Municipio"
    SET "NombreMunicipio" = "p_NombreMunicipio"
    WHERE "IdMunicipio" = "p_IdMunicipio";
END;
$$;

-- Municipios con más reservas
CREATE OR REPLACE FUNCTION public."SP_MunicipiosConMasReservas"()
RETURNS TABLE (
    "NombreMunicipio" VARCHAR(150),
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "TotalReservas" BIGINT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        m."NombreMunicipio",
        f."IdFinca",
        f."NombreFinca",
        COUNT(r."IdReserva")::BIGINT AS "TotalReservas"
    FROM public."Reserva" r
    INNER JOIN public."Finca" f ON r."IdFinca" = f."IdFinca"
    INNER JOIN public."Municipio" m ON f."IdMunicipio" = m."IdMunicipio"
    GROUP BY m."NombreMunicipio", f."IdFinca", f."NombreFinca"
    ORDER BY "TotalReservas" DESC;
END;
$$;

--------------------------------------------------------------------------------
-- 5.4 FINCAS
--------------------------------------------------------------------------------

-- Listar fincas
CREATE OR REPLACE FUNCTION public."SP_ListarFincas"()
RETURNS TABLE (
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "Direccion" VARCHAR(500),
    "InformacionAdicional" VARCHAR(500),
    "Capacidad" INT,
    "Precio" INT,
    "Estado" VARCHAR(150),
    "Calificacion" INT,
    "IdMunicipio" INT,
    "NombreMunicipio" VARCHAR(150),
    "IdPropietario" INT,
    "NombrePropietario" VARCHAR(300),
    "ApellidoPropietario" VARCHAR(300),
    "TelefonoPropietario" VARCHAR(100),
    "CorreoPropietario" VARCHAR(500)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        f."IdFinca",
        f."NombreFinca",
        f."Direccion",
        f."InformacionAdicional",
        f."Capacidad",
        f."Precio",
        f."Estado",
        f."Calificacion",
        m."IdMunicipio",
        m."NombreMunicipio",
        u."NumeroDocumento" AS "IdPropietario",
        u."NombreUsuario" AS "NombrePropietario",
        u."ApellidoUsuario" AS "ApellidoPropietario",
        u."Telefono" AS "TelefonoPropietario",
        u."Correo" AS "CorreoPropietario"
    FROM public."Finca" f
    INNER JOIN public."Municipio" m ON f."IdMunicipio" = m."IdMunicipio"
    INNER JOIN public."Usuario" u ON f."NumeroDocumentoUsuario" = u."NumeroDocumento"
    ORDER BY f."IdFinca" ASC;
END;
$$;

-- Insertar finca (retorna IdFinca)
CREATE OR REPLACE FUNCTION public."SP_InsertarFinca"(
    "p_IdMunicipio" INT,
    "p_NumeroDocumentoUsuario" INT,
    "p_NombreFinca" VARCHAR(300),
    "p_Direccion" VARCHAR(500),
    "p_InformacionAdicional" VARCHAR(500),
    "p_Capacidad" INT,
    "p_Precio" INT,
    "p_Estado" VARCHAR(150) DEFAULT 'Disponible',
    "p_Calificacion" INT DEFAULT 5
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO public."Finca" (
        "IdMunicipio", "NumeroDocumentoUsuario", "NombreFinca", "Direccion", 
        "InformacionAdicional", "Capacidad", "Precio", "Estado", "Calificacion"
    ) VALUES (
        "p_IdMunicipio", "p_NumeroDocumentoUsuario", "p_NombreFinca", "p_Direccion", 
        "p_InformacionAdicional", "p_Capacidad", "p_Precio", COALESCE("p_Estado", 'Disponible'), COALESCE("p_Calificacion", 5)
    )
    RETURNING "IdFinca" INTO v_id;
    RETURN v_id;
END;
$$;

-- Actualizar finca
CREATE OR REPLACE FUNCTION public."SP_ActualizarFinca"(
    "p_IdFinca" INT,
    "p_NombreFinca" VARCHAR(300),
    "p_Direccion" VARCHAR(500),
    "p_InformacionAdicional" VARCHAR(500),
    "p_Capacidad" INT,
    "p_Precio" INT,
    "p_Estado" VARCHAR(150)
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public."Finca"
    SET "NombreFinca" = "p_NombreFinca",
        "Direccion" = "p_Direccion",
        "InformacionAdicional" = "p_InformacionAdicional",
        "Capacidad" = "p_Capacidad",
        "Precio" = "p_Precio",
        "Estado" = "p_Estado"
    WHERE "IdFinca" = "p_IdFinca";
END;
$$;

-- Fincas más reservadas
CREATE OR REPLACE FUNCTION public."SP_FincasMasReservadas"()
RETURNS TABLE (
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "CantidadReservas" BIGINT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        f."IdFinca",
        f."NombreFinca", 
        COUNT(r."IdReserva")::BIGINT AS "CantidadReservas"
    FROM public."Reserva" r
    INNER JOIN public."Finca" f ON r."IdFinca" = f."IdFinca"
    GROUP BY f."IdFinca", f."NombreFinca"
    ORDER BY "CantidadReservas" DESC
    LIMIT 5;
END;
$$;

-- Promedio de calificación de fincas
CREATE OR REPLACE FUNCTION public."SP_PromedioCalificacionFincas"()
RETURNS TABLE (
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "PromedioCalificacion" DOUBLE PRECISION
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        f."IdFinca",
        f."NombreFinca", 
        ROUND(AVG(f."Calificacion")::NUMERIC, 2)::DOUBLE PRECISION AS "PromedioCalificacion"
    FROM public."Finca" f
    WHERE f."Calificacion" IS NOT NULL
    GROUP BY f."IdFinca", f."NombreFinca"
    ORDER BY "PromedioCalificacion" DESC;
END;
$$;

-- Total ingresos por finca
CREATE OR REPLACE FUNCTION public."SP_TotalIngresosPorFinca"()
RETURNS TABLE (
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "TotalIngresos" BIGINT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        f."IdFinca",
        f."NombreFinca", 
        COALESCE(SUM(p."Monto"), 0)::BIGINT AS "TotalIngresos"
    FROM public."Pago" p
    INNER JOIN public."Factura" fa ON p."IdFactura" = fa."IdFactura"
    INNER JOIN public."Reserva" r ON fa."IdReserva" = r."IdReserva"
    INNER JOIN public."Finca" f ON r."IdFinca" = f."IdFinca"
    WHERE p."EstadoPago" = 'Pagado'
    GROUP BY f."IdFinca", f."NombreFinca"
    ORDER BY "TotalIngresos" DESC;
END;
$$;

-- Fincas con más ingresos (Top 5)
CREATE OR REPLACE FUNCTION public."SP_FincasConMasIngresos"()
RETURNS TABLE (
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "IngresosTotales" BIGINT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        f."IdFinca",
        f."NombreFinca",
        COALESCE(SUM(p."Monto"), 0)::BIGINT AS "IngresosTotales"
    FROM public."Pago" p
    INNER JOIN public."Factura" fa ON p."IdFactura" = fa."IdFactura"
    INNER JOIN public."Reserva" r ON fa."IdReserva" = r."IdReserva"
    INNER JOIN public."Finca" f ON r."IdFinca" = f."IdFinca"
    WHERE p."EstadoPago" = 'Pagado'
    GROUP BY f."IdFinca", f."NombreFinca"
    ORDER BY "IngresosTotales" DESC
    LIMIT 5;
END;
$$;

--------------------------------------------------------------------------------
-- 5.5 IMÁGENES
--------------------------------------------------------------------------------

-- Listar imágenes
CREATE OR REPLACE FUNCTION public."SP_ListarImagenes"()
RETURNS TABLE (
    "IdImagen" INT,
    "UrlImagen" VARCHAR(500),
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "Direccion" VARCHAR(500),
    "NombreMunicipio" VARCHAR(150),
    "NombrePropietario" VARCHAR(300),
    "ApellidoPropietario" VARCHAR(300)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        i."IdImagen",
        i."UrlImagen",
        f."IdFinca",
        f."NombreFinca",
        f."Direccion",
        m."NombreMunicipio",
        u."NombreUsuario" AS "NombrePropietario",
        u."ApellidoUsuario" AS "ApellidoPropietario"
    FROM public."Imagen" i
    INNER JOIN public."Finca" f ON i."IdFinca" = f."IdFinca"
    INNER JOIN public."Municipio" m ON f."IdMunicipio" = m."IdMunicipio"
    INNER JOIN public."Usuario" u ON f."NumeroDocumentoUsuario" = u."NumeroDocumento"
    ORDER BY i."IdImagen" ASC;
END;
$$;

-- Registrar imagen (retorna IdImagen)
CREATE OR REPLACE FUNCTION public."SP_RegistrarImagen"(
    "p_UrlImagen" VARCHAR(500),
    "p_IdFinca" INT
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO public."Imagen" ("UrlImagen", "IdFinca")
    VALUES ("p_UrlImagen", "p_IdFinca")
    RETURNING "IdImagen" INTO v_id;
    RETURN v_id;
END;
$$;

-- Actualizar imagen
CREATE OR REPLACE FUNCTION public."SP_ActualizarImagen"(
    "p_IdImagen" INT,
    "p_UrlImagen" VARCHAR(500),
    "p_IdFinca" INT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public."Imagen"
    SET "UrlImagen" = "p_UrlImagen",
        "IdFinca" = "p_IdFinca"
    WHERE "IdImagen" = "p_IdImagen";
END;
$$;

--------------------------------------------------------------------------------
-- 5.6 MÉTODOS DE PAGO
--------------------------------------------------------------------------------

-- Listar métodos de pago
CREATE OR REPLACE FUNCTION public."SP_ListarMetodosDePago"()
RETURNS TABLE (
    "IdMetodoDePago" INT,
    "NombreMetodoDePago" VARCHAR(150),
    "PagoMixto" BOOLEAN
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT mp."IdMetodoDePago", mp."NombreMetodoDePago", mp."PagoMixto"
    FROM public."MetodoDePago" mp
    ORDER BY mp."IdMetodoDePago" ASC;
END;
$$;

-- Registrar método de pago (retorna IdMetodoDePago)
CREATE OR REPLACE FUNCTION public."SP_RegistrarMetodoDePago"(
    "p_NombreMetodoDePago" VARCHAR(150),
    "p_PagoMixto" BOOLEAN DEFAULT FALSE
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO public."MetodoDePago" ("NombreMetodoDePago", "PagoMixto")
    VALUES ("p_NombreMetodoDePago", COALESCE("p_PagoMixto", FALSE))
    RETURNING "IdMetodoDePago" INTO v_id;
    RETURN v_id;
END;
$$;

-- Actualizar método de pago
CREATE OR REPLACE FUNCTION public."SP_ActualizarMetodoDePago"(
    "p_IdMetodoDePago" INT,
    "p_NombreMetodoDePago" VARCHAR(150),
    "p_PagoMixto" BOOLEAN
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public."MetodoDePago"
    SET "NombreMetodoDePago" = "p_NombreMetodoDePago",
        "PagoMixto" = "p_PagoMixto"
    WHERE "IdMetodoDePago" = "p_IdMetodoDePago";
END;
$$;

--------------------------------------------------------------------------------
-- 5.7 RESERVAS
--------------------------------------------------------------------------------

-- Listar todas las reservas
CREATE OR REPLACE FUNCTION public."SP_ListarReservas"()
RETURNS TABLE (
    "IdReserva" INT,
    "FechaReserva" TIMESTAMP WITHOUT TIME ZONE,
    "FechaEntrada" TIMESTAMP WITHOUT TIME ZONE,
    "FechaSalida" TIMESTAMP WITHOUT TIME ZONE,
    "MontoReserva" INT,
    "Estado" VARCHAR(150),
    "NumeroDocumentoUsuario" INT,
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "PrecioFinca" INT,
    "EstadoFinca" VARCHAR(150),
    "NombreMunicipio" VARCHAR(150),
    "IdPropietario" INT,
    "NombrePropietario" VARCHAR(300),
    "ApellidoPropietario" VARCHAR(300),
    "NumeroDocumentoCliente" INT,
    "NombreCliente" VARCHAR(300),
    "ApellidoCliente" VARCHAR(300),
    "TelefonoCliente" VARCHAR(100),
    "CorreoCliente" VARCHAR(500)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        r."IdReserva",
        r."FechaReserva",
        r."FechaEntrada",
        r."FechaSalida",
        r."MontoReserva",
        r."Estado",
        r."NumeroDocumentoUsuario",
        f."IdFinca",
        f."NombreFinca",
        f."Precio" AS "PrecioFinca",
        f."Estado" AS "EstadoFinca",
        m."NombreMunicipio",
        propietario."NumeroDocumento" AS "IdPropietario",
        propietario."NombreUsuario" AS "NombrePropietario",
        propietario."ApellidoUsuario" AS "ApellidoPropietario",
        cliente."NumeroDocumento" AS "NumeroDocumentoCliente",
        cliente."NombreUsuario" AS "NombreCliente",
        cliente."ApellidoUsuario" AS "ApellidoCliente",
        cliente."Telefono" AS "TelefonoCliente",
        cliente."Correo" AS "CorreoCliente"
    FROM public."Reserva" r
    INNER JOIN public."Finca" f ON r."IdFinca" = f."IdFinca"
    INNER JOIN public."Municipio" m ON f."IdMunicipio" = m."IdMunicipio"
    INNER JOIN public."Usuario" propietario ON f."NumeroDocumentoUsuario" = propietario."NumeroDocumento"
    LEFT JOIN public."Usuario" cliente ON r."NumeroDocumentoUsuario" = cliente."NumeroDocumento"
    ORDER BY r."IdReserva" DESC;
END;
$$;

-- Listar reservas por usuario
CREATE OR REPLACE FUNCTION public."SP_ListarReservasPorUsuario"(
    "p_NumeroDocumentoUsuario" INT
)
RETURNS TABLE (
    "IdReserva" INT,
    "FechaReserva" TIMESTAMP WITHOUT TIME ZONE,
    "FechaEntrada" TIMESTAMP WITHOUT TIME ZONE,
    "FechaSalida" TIMESTAMP WITHOUT TIME ZONE,
    "MontoReserva" INT,
    "Estado" VARCHAR(150),
    "NumeroDocumentoUsuario" INT,
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "PrecioFinca" INT,
    "EstadoFinca" VARCHAR(150),
    "Capacidad" INT,
    "NombreMunicipio" VARCHAR(150),
    "IdPropietario" INT,
    "NombrePropietario" VARCHAR(300),
    "ApellidoPropietario" VARCHAR(300),
    "TelefonoPropietario" VARCHAR(100),
    "NumeroDocumentoCliente" INT,
    "NombreCliente" VARCHAR(300),
    "ApellidoCliente" VARCHAR(300),
    "TelefonoCliente" VARCHAR(100),
    "CorreoCliente" VARCHAR(500)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        r."IdReserva",
        r."FechaReserva",
        r."FechaEntrada",
        r."FechaSalida",
        r."MontoReserva",
        r."Estado",
        r."NumeroDocumentoUsuario",
        f."IdFinca",
        f."NombreFinca",
        f."Precio" AS "PrecioFinca",
        f."Estado" AS "EstadoFinca",
        f."Capacidad",
        m."NombreMunicipio",
        propietario."NumeroDocumento" AS "IdPropietario",
        propietario."NombreUsuario" AS "NombrePropietario",
        propietario."ApellidoUsuario" AS "ApellidoPropietario",
        propietario."Telefono" AS "TelefonoPropietario",
        cliente."NumeroDocumento" AS "NumeroDocumentoCliente",
        cliente."NombreUsuario" AS "NombreCliente",
        cliente."ApellidoUsuario" AS "ApellidoCliente",
        cliente."Telefono" AS "TelefonoCliente",
        cliente."Correo" AS "CorreoCliente"
    FROM public."Reserva" r
    INNER JOIN public."Finca" f ON r."IdFinca" = f."IdFinca"
    INNER JOIN public."Municipio" m ON f."IdMunicipio" = m."IdMunicipio"
    INNER JOIN public."Usuario" propietario ON f."NumeroDocumentoUsuario" = propietario."NumeroDocumento"
    LEFT JOIN public."Usuario" cliente ON r."NumeroDocumentoUsuario" = cliente."NumeroDocumento"
    WHERE r."NumeroDocumentoUsuario" = "p_NumeroDocumentoUsuario"
    ORDER BY r."FechaReserva" DESC;
END;
$$;

-- Registrar reserva (retorna IdReserva)
CREATE OR REPLACE FUNCTION public."SP_RegistrarReserva"(
    "p_IdFinca" INT,
    "p_NumeroDocumentoUsuario" INT,
    "p_FechaReserva" TIMESTAMP WITHOUT TIME ZONE,
    "p_FechaEntrada" TIMESTAMP WITHOUT TIME ZONE,
    "p_FechaSalida" TIMESTAMP WITHOUT TIME ZONE,
    "p_MontoReserva" INT,
    "p_Estado" VARCHAR(150) DEFAULT 'Pendiente'
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO public."Reserva" (
        "IdFinca", "NumeroDocumentoUsuario", "FechaReserva", "FechaEntrada", "FechaSalida", "MontoReserva", "Estado"
    ) VALUES (
        "p_IdFinca", "p_NumeroDocumentoUsuario", 
        COALESCE("p_FechaReserva", CURRENT_TIMESTAMP), 
        "p_FechaEntrada", "p_FechaSalida", "p_MontoReserva", COALESCE("p_Estado", 'Pendiente')
    )
    RETURNING "IdReserva" INTO v_id;
    RETURN v_id;
END;
$$;

-- Actualizar reserva
CREATE OR REPLACE FUNCTION public."SP_ActualizarReserva"(
    "p_IdReserva" INT,
    "p_IdFinca" INT,
    "p_NumeroDocumentoUsuario" INT,
    "p_FechaReserva" TIMESTAMP WITHOUT TIME ZONE,
    "p_FechaEntrada" TIMESTAMP WITHOUT TIME ZONE,
    "p_FechaSalida" TIMESTAMP WITHOUT TIME ZONE,
    "p_Estado" VARCHAR(150),
    "p_MontoReserva" INT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public."Reserva"
    SET "IdFinca" = "p_IdFinca",
        "NumeroDocumentoUsuario" = "p_NumeroDocumentoUsuario",
        "FechaReserva" = "p_FechaReserva",
        "FechaEntrada" = "p_FechaEntrada",
        "FechaSalida" = "p_FechaSalida",
        "Estado" = "p_Estado",
        "MontoReserva" = "p_MontoReserva"
    WHERE "IdReserva" = "p_IdReserva";
END;
$$;

--------------------------------------------------------------------------------
-- 5.8 FACTURAS
--------------------------------------------------------------------------------

-- Listar facturas
CREATE OR REPLACE FUNCTION public."SP_ListarFacturas"()
RETURNS TABLE (
    "IdFactura" INT,
    "FechaFactura" TIMESTAMP WITHOUT TIME ZONE,
    "Total" INT,
    "IdReserva" INT,
    "FechaReserva" TIMESTAMP WITHOUT TIME ZONE,
    "EstadoReserva" VARCHAR(150),
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "PrecioFinca" INT,
    "NombreMunicipio" VARCHAR(150),
    "IdPropietario" INT,
    "NombrePropietario" VARCHAR(300),
    "ApellidoPropietario" VARCHAR(300)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        fa."IdFactura",
        fa."FechaFactura",
        fa."Total",
        r."IdReserva",
        r."FechaReserva",
        r."Estado" AS "EstadoReserva",
        f."IdFinca",
        f."NombreFinca",
        f."Precio" AS "PrecioFinca",
        m."NombreMunicipio",
        u."NumeroDocumento" AS "IdPropietario",
        u."NombreUsuario" AS "NombrePropietario",
        u."ApellidoUsuario" AS "ApellidoPropietario"
    FROM public."Factura" fa
    INNER JOIN public."Reserva" r ON fa."IdReserva" = r."IdReserva"
    INNER JOIN public."Finca" f ON r."IdFinca" = f."IdFinca"
    INNER JOIN public."Municipio" m ON f."IdMunicipio" = m."IdMunicipio"
    INNER JOIN public."Usuario" u ON f."NumeroDocumentoUsuario" = u."NumeroDocumento"
    ORDER BY fa."IdFactura" DESC;
END;
$$;

-- Registrar factura (retorna IdFactura)
CREATE OR REPLACE FUNCTION public."SP_RegistrarFactura"(
    "p_IdReserva" INT,
    "p_FechaFactura" TIMESTAMP WITHOUT TIME ZONE,
    "p_Total" INT
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO public."Factura" ("IdReserva", "FechaFactura", "Total")
    VALUES ("p_IdReserva", COALESCE("p_FechaFactura", CURRENT_TIMESTAMP), "p_Total")
    RETURNING "IdFactura" INTO v_id;
    RETURN v_id;
END;
$$;

-- Actualizar factura
CREATE OR REPLACE FUNCTION public."SP_ActualizarFactura"(
    "p_IdFactura" INT,
    "p_IdReserva" INT,
    "p_FechaFactura" TIMESTAMP WITHOUT TIME ZONE,
    "p_Total" INT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public."Factura"
    SET "IdReserva" = "p_IdReserva",
        "FechaFactura" = "p_FechaFactura",
        "Total" = "p_Total"
    WHERE "IdFactura" = "p_IdFactura";
END;
$$;

--------------------------------------------------------------------------------
-- 5.9 PAGOS
--------------------------------------------------------------------------------

-- Listar pagos
CREATE OR REPLACE FUNCTION public."SP_ListarPagos"()
RETURNS TABLE (
    "IdPago" INT,
    "Monto" INT,
    "FechaPago" TIMESTAMP WITHOUT TIME ZONE,
    "EstadoPago" VARCHAR(150),
    "IdFactura" INT,
    "FechaFactura" TIMESTAMP WITHOUT TIME ZONE,
    "TotalFactura" INT,
    "IdReserva" INT,
    "EstadoReserva" VARCHAR(150),
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "PrecioFinca" INT,
    "NombreMunicipio" VARCHAR(150),
    "IdMetodoDePago" INT,
    "NombreMetodoDePago" VARCHAR(150),
    "PagoMixto" BOOLEAN,
    "IdPropietario" INT,
    "NombrePropietario" VARCHAR(300),
    "ApellidoPropietario" VARCHAR(300)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p."IdPago",
        p."Monto",
        p."FechaPago",
        p."EstadoPago",
        p."IdFactura",
        fa."FechaFactura",
        fa."Total" AS "TotalFactura",
        r."IdReserva",
        r."Estado" AS "EstadoReserva",
        f."IdFinca",
        f."NombreFinca",
        f."Precio" AS "PrecioFinca",
        m."NombreMunicipio",
        mp."IdMetodoDePago",
        mp."NombreMetodoDePago",
        mp."PagoMixto",
        u."NumeroDocumento" AS "IdPropietario",
        u."NombreUsuario" AS "NombrePropietario",
        u."ApellidoUsuario" AS "ApellidoPropietario"
    FROM public."Pago" p
    INNER JOIN public."Factura" fa ON p."IdFactura" = fa."IdFactura"
    INNER JOIN public."Reserva" r ON fa."IdReserva" = r."IdReserva"
    INNER JOIN public."Finca" f ON r."IdFinca" = f."IdFinca"
    INNER JOIN public."Municipio" m ON f."IdMunicipio" = m."IdMunicipio"
    INNER JOIN public."MetodoDePago" mp ON p."IdMetodoDePago" = mp."IdMetodoDePago"
    INNER JOIN public."Usuario" u ON f."NumeroDocumentoUsuario" = u."NumeroDocumento"
    ORDER BY p."IdPago" DESC;
END;
$$;

-- Registrar pago (retorna IdPago)
CREATE OR REPLACE FUNCTION public."SP_RegistrarPago"(
    "p_IdFactura" INT,
    "p_IdMetodoDePago" INT,
    "p_Monto" INT,
    "p_FechaPago" TIMESTAMP WITHOUT TIME ZONE,
    "p_EstadoPago" VARCHAR(150) DEFAULT 'Pendiente'
)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE
    v_id INT;
BEGIN
    INSERT INTO public."Pago" ("IdFactura", "IdMetodoDePago", "Monto", "FechaPago", "EstadoPago")
    VALUES ("p_IdFactura", "p_IdMetodoDePago", "p_Monto", COALESCE("p_FechaPago", CURRENT_TIMESTAMP), COALESCE("p_EstadoPago", 'Pendiente'))
    RETURNING "IdPago" INTO v_id;
    RETURN v_id;
END;
$$;

-- Actualizar pago
CREATE OR REPLACE FUNCTION public."SP_ActualizarPago"(
    "p_IdPago" INT,
    "p_IdFactura" INT,
    "p_IdMetodoDePago" INT,
    "p_Monto" INT,
    "p_FechaPago" TIMESTAMP WITHOUT TIME ZONE,
    "p_EstadoPago" VARCHAR(150)
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public."Pago"
    SET "IdFactura" = "p_IdFactura",
        "IdMetodoDePago" = "p_IdMetodoDePago",
        "Monto" = "p_Monto",
        "FechaPago" = "p_FechaPago",
        "EstadoPago" = "p_EstadoPago"
    WHERE "IdPago" = "p_IdPago";
END;
$$;

-- Pagos pendientes
CREATE OR REPLACE FUNCTION public."SP_PagosPendientes"()
RETURNS TABLE (
    "IdPago" INT,
    "IdFactura" INT,
    "IdFinca" INT,
    "NombreFinca" VARCHAR(300),
    "Monto" INT,
    "FechaPago" TIMESTAMP WITHOUT TIME ZONE,
    "EstadoPago" VARCHAR(150)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p."IdPago",
        fa."IdFactura",
        f."IdFinca",
        f."NombreFinca",
        p."Monto",
        p."FechaPago",
        p."EstadoPago"
    FROM public."Pago" p
    INNER JOIN public."Factura" fa ON p."IdFactura" = fa."IdFactura"
    INNER JOIN public."Reserva" r ON fa."IdReserva" = r."IdReserva"
    INNER JOIN public."Finca" f ON r."IdFinca" = f."IdFinca"
    WHERE p."EstadoPago" = 'Pendiente'
    ORDER BY p."IdPago" ASC;
END;
$$;

-- =============================================================================
-- 6. DATOS INICIALES (SEED DATA)
-- =============================================================================

-- Roles del sistema
INSERT INTO public."Rol" ("IdRol", "NombreRol") VALUES
(1, 'Administrador'),
(2, 'Cliente'),
(3, 'Propietario')
ON CONFLICT ("IdRol") DO NOTHING;

SELECT setval(pg_get_serial_sequence('public."Rol"', 'IdRol'), COALESCE(MAX("IdRol"), 1)) FROM public."Rol";

-- Municipios de ejemplo
INSERT INTO public."Municipio" ("IdMunicipio", "NombreMunicipio") VALUES
(1, 'Medellín'),
(2, 'Guatapé'),
(3, 'Santa Fe de Antioquia'),
(4, 'Jardín'),
(5, 'Jericó'),
(6, 'Rionegro'),
(7, 'El Peñol'),
(8, 'Barbosa'),
(9, 'Girardota'),
(10, 'Copacabana'),
(11, 'San Jerónimo'),
(12, 'La Ceja')
ON CONFLICT ("IdMunicipio") DO NOTHING;

SELECT setval(pg_get_serial_sequence('public."Municipio"', 'IdMunicipio'), COALESCE(MAX("IdMunicipio"), 1)) FROM public."Municipio";

-- Métodos de Pago
INSERT INTO public."MetodoDePago" ("IdMetodoDePago", "NombreMetodoDePago", "PagoMixto") VALUES
(1, 'Efectivo', false),
(2, 'Transferencia Bancaria', false),
(3, 'Tarjeta de Crédito', false),
(4, 'Nequi / Daviplata', true)
ON CONFLICT ("IdMetodoDePago") DO NOTHING;

SELECT setval(pg_get_serial_sequence('public."MetodoDePago"', 'IdMetodoDePago'), COALESCE(MAX("IdMetodoDePago"), 1)) FROM public."MetodoDePago";

-- Usuario Administrador Inicial por defecto
INSERT INTO public."Usuario" (
    "NumeroDocumento", "IdRol", "NombreUsuario", "ApellidoUsuario", "Telefono", "Contrasena", "Correo", "Estado"
) VALUES
(1, 1, 'Admin', 'Renfi', '3000000000', 'admin123', 'admin@renfi.com', 'Activo')
ON CONFLICT ("Correo") DO NOTHING;

SELECT setval(pg_get_serial_sequence('public."Usuario"', 'NumeroDocumento'), COALESCE(MAX("NumeroDocumento"), 1)) FROM public."Usuario";

-- =============================================================================
-- 7. CONFIGURACIÓN DE SEGURIDAD (SUPABASE RLS - ROW LEVEL SECURITY)
-- Habilita RLS pero permite el acceso completo a los roles de API y autenticados
-- para evitar respuestas vacías ('permission denied' o rows ocultas).
-- =============================================================================

ALTER TABLE public."Rol" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Usuario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Municipio" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Finca" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Imagen" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."MetodoDePago" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Reserva" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Factura" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Pago" ENABLE ROW LEVEL SECURITY;

-- Políticas permisivas (Open access para API backend y clientes Supabase autorizados)
CREATE POLICY "Permitir_Todo_Rol" ON public."Rol" FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_Todo_Usuario" ON public."Usuario" FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_Todo_Municipio" ON public."Municipio" FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_Todo_Finca" ON public."Finca" FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_Todo_Imagen" ON public."Imagen" FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_Todo_MetodoDePago" ON public."MetodoDePago" FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_Todo_Reserva" ON public."Reserva" FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_Todo_Factura" ON public."Factura" FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir_Todo_Pago" ON public."Pago" FOR ALL USING (true) WITH CHECK (true);

-- Permisos de ejecución de funciones para los roles de Supabase (anon, authenticated, service_role)
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

-- =============================================================================
-- FIN DEL SCRIPT SUPABASE POSTGRESQL RENFI
-- =============================================================================
